### ISSUE TITLE
twitter 縮圖壞掉

### ISSUE THREAD

**Issue by pofeng** [ocftw/v1.ocf.tw#37]
![image](https://user-images.githubusercontent.com/43583/204437608-877f16f3-37bb-48ae-b264-fd9537c52bbf.png)

不確定是我們語法的問題, 或是 twitter 的問題

<meta property="og:image" content="/p/intldonate/head.png" />
<meta name="twitter:image:src" content="/p/intldonate/head.png" />

**Comment by ETBlue** [comment]
this should be fixed by https://github.com/ocftw/v1.ocf.tw/commit/d9e9f5ce0b72db161d157411de9fa0efc248e852 would you check again 😅 😅 😅

**Comment by toomore** [comment]
@pofeng @ETBlue 問題可能出在目前我們的 `og:image` 是用相對路徑的問題，但 shema 規定是用 full URL，請問我們有網址參與可以加上去或是手動填上 `https://ocf.tw`？（昨天發了也是[壞的](https://twitter.com/toomore/status/1651180268861161472)）

參考資料：

1. https://stackoverflow.com/questions/9858577/open-graph-can-resolve-relative-url/9858694#9858694
2. https://stackoverflow.com/questions/62146042/can-i-use-relative-path-in-open-graph
3. https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started#opengraph

**Comment by toomore** [comment]
@ETBlue 修正方式改用 `url`, `absolute_url` 來取得完整的 URL，參考這裡的 [filter](https://jekyllrb.com/docs/liquid/filters/)，感謝！ https://github.com/ocftw/v1.ocf.tw/pull/43

**Comment by toomore** [comment]
@pofeng 看起來修好了，感謝葉子手滑直接 deploy XD
![image](https://user-images.githubusercontent.com/121504/234834447-9c664442-4b15-4828-ab1c-ff76f2ec19fb.png)
![image](https://user-images.githubusercontent.com/121504/234834369-c709e481-4de7-4bbd-82a5-9ee4c7f3c939.png)

**Comment by pofeng** [comment]
讚, 感謝三位 !!

**Comment by ETBlue** [comment]
@toomore @leaf0922 原來如此... 大感謝教學 & 補丁～～～
